# Generated by Django 5.2.17 on 2026-08-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_styles', '0003_alter_comida_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('ordem', 'id')},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
